### ISSUE TITLE
meta-api: Code Enhancements

### ISSUE THREAD

**Issue by nishant-jain-94** [nishant-jain-94/sro-ontology-manager#12]
- [x] Can have top level dedicated folders for RabbitMQ and Neo4j containing the following files *.controller.js, *.io.js *.routes.js *.*.test.js leading to removal of the following folders controllers, routes, io.

- [x] Test cases to be written for all the routes.

- [x] Need Code Level comments. 

- [ ] Need documentation for the events and api exposed.

- [x] Requires linting using ESLint Module and Airbnb style guide.

- [x] Requires lint, generate-docs scripts in package.json. Refer ontology_processors.

**Comment by chandrangreat** [comment]
Need to figure out a proper way to generate documentation using a documentation tool.
Created a new issue for that ---  #19
